baseURL = "https://yoon.ws/"
languageCode = "en-us"
title = "Pusnow"
enableGitInfo = true

[permalinks]
note = "/note/:filename/"
publication = "/publication/:filename/"

[[menu.main]]
name = "Home"
url = ""
weight = 1


[[menu.main]]
name = "Notes"
url = "note/"
weight = 2

[[menu.main]]
name = "Hiking"
url = "hiking/"
weight = 3


[[menu.main]]
name = "Tags"
url = "tags/"
weight = 4

[[menu.main]]
name = "CV"
url = "pdf/cv.pdf"
weight = 5


[params]
footer = "&copy; [Wonsup Yoon](https://yoon.ws) | [GitHub](https://github.com/pusnow) | Original theme: [Hugo xmin](https://github.com/yihui/hugo-xmin)"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.renderer]
unsafe = true
