# This is a basic workflow to help you get started with Actions

name: Build Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          
      - uses: actions/checkout@v2
          
      - name: Hugo
        uses: docker://ghcr.io/pusnow/hugo:latest

      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVKEY }}
          ref: pages
          path: pages
      - name: Deploy
        run : rsync -r --delete --exclude="CNAME" --exclude=".git" public/ pages/
      
      - name: GIT config
        working-directory: ${{github.workspace}}/pages
        shell: bash
        run : |
              git config user.email "bot@pusnow.com"
              git config user.name "Wonsup Yoon"
      
      - name: Commit
        working-directory: ${{github.workspace}}/pages
        shell: bash
        run: |
            git add -A
            git commit -m "Update from $GITHUB_SHA" --allow-empty
          
      - name: Push
        working-directory: ${{github.workspace}}/pages
        shell: bash
        run: |
            git push
      

          
